#!/usr/bin/env bash

# Algunos útiles
alias cls="clear"
alias c="clear"
alias update="sudo apt-get update && sudo apt-get upgrade -y && sudo apt autoclean"
alias version="lsb_release -d | awk '{print $2, $3, $4}' && lsb_release -c | awk '{print $2}'"
alias ports='ss -tulanp'
alias mnt="mount | awk '{if (/^\/dev/ || /^\/\//) print($1,$2,$3)} | column -t | sort'"
alias cp="cp -v"
alias mv="mv -v"

# NVIM
alias vim="nvim"
alias vi="nvim"
alias oldvim="vim"

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# List all files colorized in long format

alias ls="command ls -h ${colorflag}"
alias l="ls -lFh ${colorflag}"
alias la="ls -lAFh ${colorflag}"
alias ll="ls -lrthA ${colorflag}"

# List only directories
alias lsd="ls -lFh ${colorflag} | grep --color=never '^d'"

# List only files
alias lsf="ls -lFh ${colorflag} | grep --color=never '^-'"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Get week number
alias week='date +%V'
alias tokudate='date +"%Y-%m-%d w%V.%u %H:%M"'


# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Multipass
alias mp='multipass'
alias mpd='multipass delete'
alias mpe='multipass exec'
alias mpi='multipass info'
alias mpl='multipass launch'

# Docker

function dnames-fn {
	for ID in `docker ps | awk '{print $1}' | grep -v 'CONTAINER'`
	do
    	docker inspect $ID | grep Name | head -1 | awk '{print $2}' | sed 's/,//g' | sed 's%/%%g' | sed 's/"//g'
	done
}

function dclean-fn {
	echo "\n\nEliminando contenedores muertos"
	docker rm -f $(docker ps -aq -f status=exited)
	echo "\n\nEliminando imágenes <none>"
	docker rmi $(docker images -q- f dangling=true)
	echo "\n\nBorrando los volúmenes sin usar"
	docker volume prune -f
  echo "\n\nBorrando las redes sin usar"
	docker network prune -f
}

function dip-fn {
  for ID in `docker ps -q`
	do
		docker inspect --format '{{.Id}} {{ .Name }} {{ .Config.Image }} {{ range .NetworkSettings.Networks }}{{.IPAddress}} {{.MacAddress}}{{ end }}' $ID | awk '{print(substr($1,1,8),substr($2,2),$3,$4,$5)}' | column -t | sort -k 4
	done
}

alias dps="docker ps"
alias dpsa="docker ps -a"
alias drmi="docker rmi"

alias dc="docker-compose"
alias dcu="docker-compose up -d"
alias dcd="docker-compose down"

alias dexe="docker exec"
alias dins="docker inspect"
alias dimg="docker images"
alias dins="docker inspect"

alias dlog="docker logs -f"
alias dsp="docker system prune --all"
alias dnames=dnames-fn
alias dclean=dclean-fn
alias dip=dip-fn

alias drmi_basura='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'

# GIT

alias g="git"

# Para obetener el ping al gateway y a Internet 1.1.1.1
# alias pingme=ping_gateway_internet

# Archivos de configuración
alias i3config="vi $HOME/.config/i3/config"

# Networking & IP addresses
alias NetExtIP="curl ipinfo.io/ip"
alias NetIntIPall="ip a |grep 'inet '| awk '{print \$NF,\$2}'"
alias NetIntGW="ip r | grep default | cut -d' ' -f 3"
alias NetIntIPv4='hostname -I | cut -d" " -f1'
alias NetIntIPv6="ip a |grep 'inet6 '| awk '{print \$NF,\$2}'"

# Identificadores
alias ventana="xprop | grep CLASS"
alias tecla="xev | grep keysym"

# Kubernetes
alias kubectl='kubecolor'
alias k='kubectl'
alias kg='kubectl get'
alias kgp='kubectl get pod'
alias kgpw='kubectl get pod -o wide'
alias kgd='kubectl get deploy'
alias kgs='kubectl get service'
alias kgj='kubectl get jobs'

alias kapp='kubectl apply -f'
alias kdel='kubectl delete -f'
